# This is used to control dependencies and liter configuration
[project]
name = "kernel-src-tree-tools"
requires-python = ">=3.10"
readme = "README.md"
version = "0.0.1"
dependencies = [
	"gitpython",
	"click",
	"pathlib3x",
	"python3-wget",
	"oyaml",
	"pexpect",
	"jira",
	"requests",
	"more_itertools"
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "ruff",
    "pytest",
    "pytest-cov",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Ignore the `line-too-long` for now
ignore = ["E501"]

[tool.setuptools]
# suppress error: Multiple top-level packages
py-modules = []

[tool.setuptools.packages.find]
where = ["."]
include = ["kt*"]

[tool.setuptools.package-data]
"kt" = ["data/*.yaml"]

[project.scripts]
kt = "kt.kt:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra -q"

[tool.coverage.run]
source = ["."]
omit = ["tests/*", "venv/*"]
branch = true

[tool.coverage.report]
show_missing = true
skip_empty = true
