name: PR Pre Checks

on:
  pull_request:
  push:
    branches:
      - mainline

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.11'

      - name: Create Python Venv
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

      - name: Install Python deps
        run: |
          python -m pip install -e ".[dev]"
          python -m pip list

      - name: Lint
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure --verbose --color=always

      - name: Test
        run: |
          pytest --cov --cov-report=term --cov-report=markdown:coverage.md

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: coverage.md
          retention-days: 30
